// AUTO-GENERATED by `make generate_root_hints`
// (scripts/generate_root_hints.py) from the IANA root hints file [1].
// DO NOT EDIT BY HAND; re-run the generator to refresh.
//
// [1]: https://www.internic.net/domain/named.root
//
// IPv4 glue addresses of the 13 DNS root name servers
// (a.root-servers.net through m.root-servers.net). `adig +trace` uses these
// to seed iterative resolution from the root. The root-zone addresses change
// very rarely; regenerate after a root-zone renumbering.
#pragma once

#include <string_view>

namespace ag::adig::root_hints {

struct RootServer {
    char id;             // single-letter identifier ('a'..'m')
    std::string_view ip; // IPv4 address
};

inline constexpr RootServer ROOT_SERVERS[] = {
        {'a', "198.41.0.4"},
        {'b', "170.247.170.2"},
        {'c', "192.33.4.12"},
        {'d', "199.7.91.13"},
        {'e', "192.203.230.10"},
        {'f', "192.5.5.241"},
        {'g', "192.112.36.4"},
        {'h', "198.97.190.53"},
        {'i', "192.36.148.17"},
        {'j', "192.58.128.30"},
        {'k', "193.0.14.129"},
        {'l', "199.7.83.42"},
        {'m', "202.12.27.33"},
};

} // namespace ag::adig::root_hints
