---
version: 2
plan:
  project-key: CL
  key: DNSIV
  name: DnsLibs - Increment version
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - DL - Increment version
DL - Increment version:
  key: JOB1
  docker:
    image: adguard/core-libs:latest
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
      ${bamboo.git.cache.directory}: ${bamboo.git.cache.directory}
      ${system.HOME}/.ssh: /root/.ssh
    docker-run-arguments: []
  tasks:
  - !include docker-clean.yaml
  - checkout:
      repository: dns-libs
      path: dns-libs
      force-clean-build: 'true'
      description: Checkout
  - checkout:
      repository: dns-libs-private
      path: dns-libs-private
      force-clean-build: 'true'
      description: Checkout
  - script:
      interpreter: SHELL
      scripts:
      - |-
        set -x

        git config user.name "Bamboo"
        git config user.email "Bamboo"

        cp ../dns-libs-private/* .

        if [ ${bamboo_custom_version} = "none" ]; then
            bamboo_custom_version=
        fi

        ./increment_version.sh ${bamboo_custom_version} || exit 1

        git remote set-url origin ${bamboo_planRepository_repositoryUrl}
        git pull
        git reset
        git add platform/android/dnsproxy/lib/build.gradle
        git add platform/mac/framework/CMakeLists.txt
        git add platform/windows/capi/src/ag_dns.rc
        git add platform/windows/cs/Adguard.Dns/SolutionInfo.cs
        git add common/include/dns/common/version.h

        case "${bamboo_repository_branch_name}" in
        master|stable-*)

            ./increment_conan_version.sh ${bamboo_custom_version} || exit 1

            git add conandata.yml
            git commit -m "skipci: Automatic version increment by Bamboo"
            git push

        esac
      working-dir: dns-libs
      description: Increment version
  requirements:
  - adg-privileged-docker
  artifact-subscriptions: []
variables:
  custom.version: 'none'
repositories:
- dns-libs:
    scope: global
- dns-libs-private:
    scope: global
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
