---
version: 2
plan:
  project-key: CL
  key: DTR
  name: DnsLibs - Tag release
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Tag release
Tag release:
  key: JOB1
  docker:
    image: adguard/core-libs:2.4
    docker-run-arguments: []
  tasks:
  - !include docker-clean.yaml
  - checkout:
      description: Checkout Default Repository
  - checkout:
      repository: git-scripts
      path: git-scripts
  - script:
      interpreter: SHELL
      scripts:
      - |-
        case "${bamboo_repository_branch_name}" in
        master|stable-*)
            ./git-scripts/git_kit.sh pull ${bamboo_planRepository_repositoryUrl}
            VER=$(sed -ne '/version =/s/.* '\''\(.*\)'\'',.*/\1/p' platform/android/dnsproxy/lib/build.gradle)
            git tag v$VER || true
            git push origin v$VER
            echo dnslibs.version=$VER > inject.txt
        esac
  - inject-variables:
      file: inject.txt
      scope: RESULT
      namespace: inject
  requirements:
  - adg-privileged-docker
  artifact-subscriptions: []
repositories:
- dns-libs:
    scope: global
- git-scripts:
    scope: global
triggers: []
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
