---
version: 2
plan:
  project-key: CL
  key: DNSUCR
  name: DnsLibs - Upload conan recipes
stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Default Job
Default Job:
  key: JOB1
  docker:
    image: adguard/core-libs:2.6
    docker-run-arguments: []
  tasks:
    - !include docker-clean.yaml
    - checkout
    - checkout:
        repository: git-scripts
        path: git-scripts
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            ./git-scripts/git_kit.sh pull ${bamboo_planRepository_repositoryUrl}

            conan remote add --index 0 art ${bamboo.conanRepoUrl} || true

            # Export packages
            cd scripts

            python3 -m pip install -r requirements.txt
            ./export_conan.py

            cd ..
            ./bamboo-specs/scripts/conan_upload_and_cleanup.sh
  requirements:
    - adg-privileged-docker
  artifact-subscriptions: []
repositories:
  - dns-libs:
      scope: global
  - git-scripts:
      scope: global
branches:
  create: manually
  delete: never
  link-to-jira: true
triggers: []
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
