---
version: 2
plan:
  project-key: CL
  key: DNSWL
  name: DnsLibs - Windows library
  description: Windows library
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - DL - Win tests and deploy
DL - Win tests and deploy:
  key: JOB1
  tasks:
  - checkout:
      path: dns-libs
      force-clean-build: 'true'
      description: Checkout main repository
  - script:
      interpreter: BINSH_OR_CMDEXE
      scripts:
      - |-
        call vcvarsamd64_x86

        python -m venv venv --clear
        call .\venv\Scripts\activate
        pip install conan --upgrade
        conan remove -c "*"

        set CMAKE=cmake
        set CTEST=ctest
        set CMAKE_MAKE_PROGRAM=ninja
        set CMAKE_MAKE_FLAGS=""
        set CMAKE_GENERATOR="Ninja"
        set CL_GIT_ROOT=%cd%
        cd %bamboo_winProjectDir%/capi
        set CL_ROOT=%cd%

        if exist build\ rmdir /s /q build || exit /b 1
        mkdir build || exit /b 1
        cd build || exit /b 1

        %CMAKE% -DCMAKE_BUILD_TYPE=%bamboo_cmakeBuildProfile% ^
            -DCMAKE_USE_OPENSSL=ON ^
            -DCMAKE_C_COMPILER="cl.exe" ^
            -DCMAKE_CXX_COMPILER="cl.exe" ^
            -DCONAN_HOST_PROFILE="%CL_GIT_ROOT%/conan/profiles/windows-msvc.jinja;auto-cmake" ^
            -DCMAKE_MAKE_PROGRAM=%CMAKE_MAKE_PROGRAM% ^
            -G "%CMAKE_GENERATOR%" ^
            ..

        rem Target "tests" depends on everything, so this will also build AdguardDns.dll
        %CMAKE_MAKE_PROGRAM% tests || exit /b 1
        %CTEST% -D ExperimentalTest --no-compress-output || exit /b 1
        deactivate
      working-dir: dns-libs
      description: Compile and run tests
  - script:
      interpreter: BINSH_OR_CMDEXE
      scripts:
        - |-
          call vcvars64
          call .\venv\Scripts\activate
          conan remove -c "*"

          set CMAKE=cmake
          set CTEST=ctest
          set CMAKE_MAKE_PROGRAM=ninja
          set CMAKE_MAKE_FLAGS=""
          set CMAKE_GENERATOR="Ninja"
          set CL_GIT_ROOT=%cd%
          cd %bamboo_winProjectDir%/capi
          set CL_ROOT=%cd%

          if exist build64\ rmdir /s /q build64 || exit /b 1
          mkdir build64 || exit /b 1
          cd build64 || exit /b 1
          
          %CMAKE% -DCMAKE_BUILD_TYPE=%bamboo_cmakeBuildProfile% ^
              -DCMAKE_USE_OPENSSL=ON ^
              -DCMAKE_C_COMPILER="cl.exe" ^
              -DCMAKE_CXX_COMPILER="cl.exe" ^
              -DCMAKE_MAKE_PROGRAM=%CMAKE_MAKE_PROGRAM% ^
              -DCONAN_HOST_PROFILE="%CL_GIT_ROOT%/conan/profiles/windows-msvc.jinja;auto-cmake" ^
              -G "%CMAKE_GENERATOR%" ^
              ..
          
          rem Target "tests" depends on everything, so this will also build AdguardDns64.dll
          %CMAKE_MAKE_PROGRAM% tests || exit /b 1
          %CTEST% -D ExperimentalTest --no-compress-output || exit /b 1
          deactivate
      working-dir: dns-libs
      description: Compile and run tests (x64)
  - script:
      interpreter: BINSH_OR_CMDEXE
      scripts:
      - |-
        call vcvarsamd64_x86
        set CL_GIT_ROOT=%cd%
        cd %bamboo_winProjectDir%
        set CL_ROOT=%cd%
        cd cs\Adguard.Dns
        REM build csharp library
        del /s *.nupkg
        REM set NUGET_PACKAGES=c:\builder\BambooNuGetPackages
        set NUGET_PACKAGES=%cd%/packages
        nuget restore
        msbuild Adguard.Dns.Tests /t:Build /t:Test /p:Configuration=Release /p:Platform=AnyCPU || exit /b 1
        exit 0
      working-dir: dns-libs
      description: Build C#library and Run C# tests
  final-tasks:
  - any-task:
      plugin-key: fr.cstb.bamboo.plugins.ctest.bamboo-ctest-plugin:test
      configuration:
        testFilePathPattern: '**/Testing/*/*.xml'
  - any-task:
      plugin-key: com.atlassian.bamboo.plugin.dotnet:nunit
      configuration:
        testResultsDirectory: '**/Adguard.Dns.Tests/TestResult.xml'
        pickupOutdatedFiles: 'false'
  - script:
      interpreter: SHELL
      scripts:
      - |-
        call .\venv\Scripts\activate
        REM Upload built binaries
        conan remote login art "%bamboo_artifactoryUser%" --password "%bamboo_artifactoryPassword%"
        conan upload -r art -c "*" 1>&2
        REM Clean up local cache
        conan remove -c "*"
        deactivate
      working-dir: dns-libs
      description: Conan upload and cleanup
  requirements:
  - system.builder.msbuild.MSBuild v15.0 (32bit)
  artifact-subscriptions: []
variables:
  cmakeBuildProfile: RelWithDebInfo
  sentryAuthToken: 65da97ad9f9542e9ab349b380baef027c0b9a0f46dbb4999a27c5971329949f1
  winProjectDir: platform/windows
repositories:
- dns-libs:
    scope: global
- dns-libs-private:
    scope: global
branches:
  create: for-pull-request
  delete:
    after-deleted-days: 4
    after-inactive-days: 30
  integration:
    push-on-success: false
    merge-from: DnsLibs - Windows Library
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
