#!/usr/bin/env python3

"""
Regenerate tools/adyg/root_servers.h from the IANA root hints.

The DNS root name servers' addresses are published by IANA in the "root
hints" file (a.k.a. named.cache / named.root) [1]. This script fetches that
file, extracts the IPv4 (A) glue records for the 13 root servers
(a.root-servers.net .. m.root-servers.net) and writes them as a constexpr
data table into tools/adyg/root_servers.h.

The generated header is checked into the repository so that ordinary builds
and tests never need network access. Run this script (via
`make generate_root_hints`) only when you want to refresh the list, e.g.
after a root-zone renumbering.

Usage:
    generate_root_hints.py [input-file]

When `input-file` is omitted the root hints are downloaded from IANA. An
explicit file path allows offline regeneration (handy for testing the parser
without hitting the network).

[1]: https://www.internic.net/domain/named.root
"""

import os
import re
import sys
import urllib.request

WORK_DIR = os.path.dirname(os.path.realpath(__file__))
PROJECT_DIR = os.path.dirname(WORK_DIR)
HEADER_PATH = os.path.join(PROJECT_DIR, "tools", "adyg", "root_servers.h")
ROOT_HINTS_URL = "https://www.internic.net/domain/named.root"
ROOT_SERVER_IDS = "abcdefghijklm"
FETCH_TIMEOUT = 30

# Matches e.g. `A.ROOT-SERVERS.NET.   3600000   A   198.41.0.4`
# (the optional `IN` class token covers variants that include it).
RECORD_RE = re.compile(
    r"^([a-m])\.ROOT-SERVERS\.NET\.\s+\d+\s+(?:IN\s+)?A\s+([0-9.]+)\s*$",
    re.IGNORECASE,
)

HEADER_PREFIX = """\
// AUTO-GENERATED by `make generate_root_hints`
// (scripts/generate_root_hints.py) from the IANA root hints file [1].
// DO NOT EDIT BY HAND; re-run the generator to refresh.
//
// [1]: https://www.internic.net/domain/named.root
//
// IPv4 glue addresses of the 13 DNS root name servers
// (a.root-servers.net through m.root-servers.net). `adyg +trace` uses these
// to seed iterative resolution from the root. The root-zone addresses change
// very rarely; regenerate after a root-zone renumbering.
#pragma once

#include <string_view>

namespace ag::adyg::root_hints {

struct RootServer {
    char id;             // single-letter identifier ('a'..'m')
    std::string_view ip; // IPv4 address
};

inline constexpr RootServer ROOT_SERVERS[] = {
"""

HEADER_SUFFIX = "};\n\n} // namespace ag::adyg::root_hints\n"


def parse_root_hints(text):
    """
    Parse the IANA root hints `text` into an ordered {id: ip} mapping for IPv4.

    Returns the servers keyed by their lowercase single-letter id ('a'..'m').
    Raises ValueError when the set of ids is not exactly the 13 expected roots.
    """
    servers = {}
    for line in text.splitlines():
        match = RECORD_RE.match(line)
        if match is not None:
            servers[match.group(1).lower()] = match.group(2)
    missing = {c for c in ROOT_SERVER_IDS if c not in servers}
    extra = set(servers) - set(ROOT_SERVER_IDS)
    if missing or extra:
        raise ValueError(
            "root hints id set mismatch: missing=%s extra=%s"
            % (sorted(missing), sorted(extra))
        )
    return servers


def render_header(servers):
    """Render the constexpr data-table header text from `servers` (id->ip)."""
    lines = [HEADER_PREFIX]
    for cid in ROOT_SERVER_IDS:
        lines.append("        {'%s', \"%s\"},\n" % (cid, servers[cid]))
    lines.append(HEADER_SUFFIX)
    return "".join(lines)


def read_root_hints(input_file):
    """Return the raw root hints text from `input_file` or the IANA URL."""
    if input_file is not None:
        with open(input_file, "r", encoding="ascii") as handle:
            return handle.read()
    with urllib.request.urlopen(ROOT_HINTS_URL, timeout=FETCH_TIMEOUT) as response:
        return response.read().decode("ascii")


def write_if_changed(path, content):
    """Write `content` to `path` only when it differs from the current file."""
    if os.path.exists(path):
        with open(path, "r", encoding="ascii") as handle:
            if handle.read() == content:
                print("%s is up to date." % path)
                return False
    with open(path, "w", encoding="ascii") as handle:
        handle.write(content)
    return True


def main(argv):
    input_file = argv[1] if len(argv) > 1 else None
    text = read_root_hints(input_file)
    servers = parse_root_hints(text)
    content = render_header(servers)
    changed = write_if_changed(HEADER_PATH, content)
    if changed:
        print("Wrote %s (%d root servers)." % (HEADER_PATH, len(servers)))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv))
    except (ValueError, OSError) as err:
        print("error: %s" % err, file=sys.stderr)
        sys.exit(1)
