set(CMAKE_C_FLAGS_RELWITHDEBINFO "/O2 /Ob2 /Oy- /GR /MT /Z7 /EHs-c- -D_HAS_EXCEPTIONS=0 /W0 /DNDEBUG")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "/O2 /Ob2 /Oy- /GR /MT /Z7 /EHs-c- -D_HAS_EXCEPTIONS=0 /std:c++17 /W0 /DNDEBUG")
set(CMAKE_VERBOSE_MAKEFILE TRUE CACHE BOOL "Verbose Makefile")
