name: Check CHANGELOG and auto-tag

on:
  push:
    branches:
      - master
      - 'stable-*'

jobs:
  autotag:
    name: Check CHANGELOG and auto-tag
    if: github.repository == 'AdGuardSoftwareLimited/dns-libs'
    uses: AdGuardSoftwareLimited/native-libs-common/.github/workflows/autotag.yml@master
    secrets: inherit
    permissions:
      contents: write
