name: Create release PR

on:
  workflow_dispatch:
    inputs:
      part:
        description: 'Version part to increment'
        required: true
        default: 'default'
        type: choice
        options:
          - major
          - minor
          - default
      level:
        description: 'Release level'
        required: true
        default: 'default'
        type: choice
        options:
          - default
          - rc
          - release

jobs:
  create-release-pr:
    name: Create release PR
    if: github.repository == 'AdGuardSoftwareLimited/dns-libs'
    uses: AdGuardSoftwareLimited/native-libs-common/.github/workflows/create-release-pr.yml@master
    with:
      part: ${{ inputs.part }}
      level: ${{ inputs.level }}
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
      id-token: write
