name: Increment version

on:
  push:
    branches:
      - master
      - 'stable-*'
      - 'dev-*'
  workflow_dispatch:
    inputs:
      custom_version:
        description: 'Custom version (leave empty for auto-increment)'
        required: false
        default: ''

jobs:
  increment-version:
    name: Increment version
    if: github.repository == 'AdGuardSoftwareLimited/dns-libs'
    uses: AdGuardSoftwareLimited/actions/.github/workflows/git-commit-push.yml@master
    with:
      runs-on: '["team-corelibs"]'
      script: |
        ./scripts/increment_version.sh ${{ inputs.custom_version }}
      committed-files: >-
        conandata.yml
        platform/android/dnsproxy/lib/build.gradle
        platform/mac/framework/CMakeLists.txt
        platform/windows/capi/src/ag_dns.rc
        platform/windows/cs/Adguard.Dns/SolutionInfo.cs
        common/include/dns/common/version.h
        CHANGELOG.md
      commit-message: '[skip ci] Automatic version increment'
    secrets: inherit
    permissions:
      contents: write
      id-token: write

  trigger-after-increment-version:
    name: Trigger after version increment actions
    needs: increment-version
    runs-on: [team-corelibs]
    steps:
      - name: Trigger upload-conan-recipes workflow
        uses: actions/github-script@v8
        with:
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'After increment version',
            })
    permissions:
      contents: write
