name: Mirror to public repository

on:
  push:
    branches:
      - master
      - 'stable-*'
      - 'dev-*'
    tags:
      - '*'
  workflow_dispatch:
  repository_dispatch:
    types:
      - After increment version

jobs:
  mirror:
    name: Mirror to public repository
    if: github.repository == 'AdGuardSoftwareLimited/dns-libs'
    uses: AdGuardSoftwareLimited/actions/.github/workflows/mirror.yml@master
    with:
      target_repo: 'git@github.com:AdguardTeam/DnsLibs.git'
      refspecs: '+refs/heads/*:refs/heads/* +refs/notes/*:refs/notes/* +refs/tags/*:refs/tags/* ^refs/tags/*@swift-6'
    secrets: inherit
    permissions:
      contents: read
      id-token: write
